django/giftlist/urls.py
from django.urls import path
from . import views

app_name = 'giftlist'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/deletegift/', views.deleteGift, name='deletegift'),
    path('groupresults/', views.groupResults, name='groupresults'),
    path('<int:id>/sendrequest/', views.send_group_request, name='send_group_request'),
    path('<int:new_member_id>/<int:requested_group_id>/<int:group_request_id>/acceptrequest/', views.accept_group_request, name='accept_group_request'),
    path('grouprequests/', views.groupRequests, name='grouprequests'),
    path('creategroup', views.createGroup, name='creategroup'),
    path('<group>/grouplist/', views.groupLlist, name='grouplist'),
    path('memberlist/<User>', views.memberGiftList, name='membergiftlist'),
    path('addshoppinglist/<member>/<int:gift>', views.add_gift_to_shoppinglist, name='addshoppinglist'),
    path('<int:id>/<group>/deleteshoppinglist/', views.delete_gift_from_shoppinglist, name='deleteshoppinglist'),
]

django/munera/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('',include('giftlist.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

django/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

django/user/models.py
from django.db import models
from django.conf import settings

# Create your models here.

django/user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout
from . import models

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('giftlist:home')

    else:
        form = UserCreationForm()
        context = {'form': form}
        return render(request, 'registration/signup.html', context)


def logout_view(request):
    logout(request)
    return redirect('giftlist:home')

django/user/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Home</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'giftlist:home' %}">Munera</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <a class="nav-link" href="{% url 'giftlist:grouprequests' %}">Requests</a>
        <a class="nav-link text-danger" href="{% url 'user:logout' %}">Logout</a>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock%}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>
</body>

</html>