django/giftlist/urls.py
from django.urls import path
from . import views

app_name = 'giftlist'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/deletegift/', views.deleteGift, name='deletegift'),
    path('groupresults/', views.groupResults, name='groupresults'),
    path('<int:id>/sendrequest/', views.send_group_request, name='send_group_request'),
    path('<int:new_member_id>/<int:requested_group_id>/<int:group_request_id>/acceptrequest/', views.accept_group_request, name='accept_group_request'),
    path('grouprequests/', views.groupRequests, name='grouprequests'),
    path('creategroup', views.createGroup, name='creategroup'),
    path('<group>/grouplist/', views.groupLlist, name='grouplist'),
    path('memberlist/<User>', views.memberGiftList, name='membergiftlist'),
    path('addshoppinglist/<member>/<int:gift>', views.add_gift_to_shoppinglist, name='addshoppinglist'),
    path('<int:id>/<group>/deleteshoppinglist/', views.delete_gift_from_shoppinglist, name='deleteshoppinglist'),
]

django/munera/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('',include('giftlist.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

django/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

django/giftlist/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Gift(models.Model):
        user = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE
        )

        selected = models.BooleanField(default=False)

        name = models.CharField(max_length=30)
        price = models.DecimalField(max_digits=6, decimal_places=2)
        link = models.CharField(max_length=2083)

        def __str__(self):
                return self.name

class ShoppingList(models.Model):
        gift = models.ForeignKey(Gift,
                on_delete=models.CASCADE
        )
        buyer = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE
        )



class UserGroup(models.Model):
    admin = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE
        )

    group_name = models.CharField(max_length=30)

    def __str__(self):
        		return self.group_name

class GroupMember(models.Model):
    member = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE
        )
    group = models.ForeignKey(UserGroup, on_delete=models.CASCADE)

    class Meta:
            unique_together = ('member', 'group')

class GroupMemberRequest(models.Model):
    to_group = models.ForeignKey(UserGroup, on_delete=models.CASCADE, related_name='to_group')
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_group')
    timestamp = models.DateTimeField(auto_now_add=True) 

    class Meta:
            unique_together = ('to_group', 'from_user')

    def __str__(self):
	    return "From {}, to {}".format(self.from_user.username, self.to_group.group_name)

    

django/giftlist/forms.py
from django import forms
from . import models

class AddGift(forms.ModelForm):
    class Meta:
        model = models.Gift
        fields = ['name', 'price', 'link', 'user']

        widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'price': forms.TextInput(attrs={'class': 'form-control'}),
                'link': forms.TextInput(attrs={'class': 'form-control'}),
            }
        

class AddGroupMember(forms.ModelForm):
    class Meta:
        model = models.GroupMember
        fields = ['member','group']

class CreateGroup(forms.ModelForm):
    class Meta:
        model  = models.UserGroup
        fields = ['admin','group_name']

        widgets = {
                'group_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Create Group'}),
            }

django/giftlist/views.py
# Django
from django.http import HttpResponse
from django.shortcuts import ( render, redirect, get_object_or_404 )
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User as user_model

# local Django
from .models import GroupMember, Gift, UserGroup, ShoppingList, GroupMemberRequest
from .forms import AddGift, CreateGroup, AddGroupMember



# Create your views here.
@login_required(login_url='/accounts/login/')
def home(request):
    """
    Returns the home page if the user is authinticated.
    """

    user = request.user.id
    print("this is from: ")
    print(user)

    if request.method == 'POST':

        request.POST = request.POST.copy()
        request.POST.__setitem__('user',user)
        
        add_gift_form = AddGift(request.POST)
        print("Fuck: ")
        print(request.POST)
       
        if add_gift_form.is_valid():
            gift = add_gift_form.save()
            gift.save()
            return redirect('giftlist:home')

    else:
        user = request.user
        create_group_form = CreateGroup()
        user_groups = GroupMember.objects.filter(member=user)
        print(user)
        gifts = Gift.objects.filter(user=user)
        add_gift_form = AddGift()
        context = {'create_group_form':create_group_form, 'groups':user_groups,'gifts': gifts, 'add_gift_form': add_gift_form}
        print(gifts)
        return render(request, 'giftlist/home.html', context)

def deleteGift(request,id):
    """
    Deletes a gift the logined user gift list.
    """
    object = get_object_or_404(Gift, pk=id)
    object.delete()
    return redirect('giftlist:home')

def groupResults(request):
    """
    Returns a list of groups that the current user is apart of.
    """
    user = request.user

    if request.method == 'POST':
        form = AddGroupMember(request.POST)
        if form.is_valid():
            group_member = form.save(commit=False)
            group_member.member = user
            group_member.save()
            return redirect('giftlist:home')


    else:
        form = AddGroupMember()
        query = request.GET.get('q')
        results = UserGroup.objects.filter(Q(group_name__icontains=query))
        context = {'form': form, 'results': results}
        return render(request, 'group/groupresults.html', context)

def createGroup(request):
    """
    Creates a group and adds the creator of the group as the first member.
    """
    user = request.user
    user_id = user.id
    request.POST = request.POST.copy()
    request.POST.__setitem__('admin',user_id)
    group_name = request.POST['group_name']
    
    
        
    create_group_form = CreateGroup(request.POST)
       
    if create_group_form.is_valid():
        group = create_group_form.save()
        group.save()

    group = UserGroup.objects.get(group_name=group_name, admin=user_id)
    print("look:")
    print(group.id)
    member = GroupMember.objects.create(member=user, group=group)
    
    return redirect('giftlist:home')

def groupLlist(request, group):
    user = request.user
    group_object = get_object_or_404(UserGroup, group_name=group)
    
    members = GroupMember.objects.filter(group=group_object)
    shoppinglist = ShoppingList.objects.filter(buyer=user)

    context = {'group':group,'members': members, 'shoppinglist':shoppinglist}
    return render(request, 'giftlist/grouplist.html', context)

def memberGiftList(request, User):
    member = User
    print("this member was sent thru the url:"+ member)

    person = user_model.objects.get(username="{0}".format(str(member)))
    print("I got this user from my query: {0}".format(person.id))
    gifts = Gift.objects.filter(user=person.id)
    context = {'member': member, 'gifts': gifts}
    return render(request, 'giftlist/membergiftlist.html', context)

def add_gift_to_shoppinglist(request, member, gift):
    user = request.user
    gift = Gift.objects.get(pk=gift)
    shoppinglist = ShoppingList.objects.create(gift = gift,buyer = user)
    gift.selected = True
    gift.save()
    return redirect('giftlist:membergiftlist', member)

def delete_gift_from_shoppinglist(request,id,group):
    object = get_object_or_404(ShoppingList, gift=id)
    object.delete()

    gift = Gift.objects.get(pk=id)
    gift.selected = False
    gift.save()
    return redirect('giftlist:grouplist',group)

def groupRequests(request):
    user = request.user.id
    groups = list(UserGroup.objects.filter(admin=user))
    group_requests = list(GroupMemberRequest.objects.filter(to_group__in=groups))
    context = {'group_requests': group_requests}
    return render(request, 'giftlist/grouprequests.html',context)


def send_group_request(request, id):
    requested_group_id = id
    group = get_object_or_404(UserGroup, pk=requested_group_id)
    user = request.user

    obj, created = GroupMemberRequest.objects.get_or_create(
        from_user=user,
        to_group=group
    )
    
    return redirect('giftlist:home') 

def accept_group_request(request, new_member_id, requested_group_id, group_request_id):
    """
    Accept a User's request to a User Group.
    """
    new_member_id = new_member_id
    requested_group_id = requested_group_id
    group_request_id = group_request_id

    new_member = get_object_or_404(user_model, pk=new_member_id)
    requested_group = get_object_or_404(UserGroup, pk=requested_group_id)  

    new_group_member = GroupMember(member=new_member,group=requested_group)
    new_group_member.save()

    group_request = get_object_or_404(GroupMemberRequest, pk=group_request_id)
    group_request.delete()

    return redirect('giftlist:home')

django/giftlist/templates/giftlist/grouplist.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">Group</h1>

<h2>Memeber List</h2>
<ul class="list-group">
  {% for member in members %}
  <li class="list-group-item"><a href="{% url 'giftlist:membergiftlist' member.member %}">{{member.member}}</a></li>
  {% endfor %}
</ul>
<h2>Shopping List</h2>
<ul class="list-group">
  {% for gift in shoppinglist %}
  <li class="list-group-item d-flex align-items-center justify-content-between">
    <a href="">{{gift.gift}}</a>
    <a class="btn btn-danger" href="{% url 'giftlist:deleteshoppinglist' gift.gift.id group %}">X</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

django/giftlist/templates/giftlist/grouprequests.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center">Group Request</h1>
  <ul class="list-group">
    {%  for group_request in group_requests %}
    <li class="list-group-item d-flex align-items-center justify-content-between">{{group_request.from_user}} for {{group_request.to_group}} 
      <div>
        <a class="btn btn-success" href="{% url 'giftlist:accept_group_request' group_request.from_user.id group_request.to_group.id group_request.id %}">Approve</a>
      </div> 
    </li>
    {% endfor %}
  </ul>
{% endblock %}

django/giftlist/templates/giftlist/home.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">Home</h1>

<h2>Group List</h2>

<!-- Group List -->
<ul class="list-group">
  {% for group in groups %}
  <li class="list-group-item"><a href="{% url 'giftlist:grouplist' group.group %}">{{group.group}}</a></li>
  {% endfor %}
</ul>

<div class="row mt-3">
  <div class="col-sm-12 col-md-6">
    
    <!-- Search Group Form -->
    <form class="form mx-auto" method="Get" action="{% url 'giftlist:groupresults' %}">
      {% csrf_token %}
      <div class="form-group mb-2">
        <input class="form-control" id="group_search_box" type="text" name="q" placeholder="Search Group">
      </div>
      <input type="submit" class="btn btn-secondary mb-2" value="Search">
    </form>
  </div>
  <div class="col-sm-12 col-md-6">
    
    <!-- Create Group Form -->
    <form class="form mx-auto" action="{% url 'giftlist:creategroup' %}" method="post">
      {% csrf_token %}
      <div class="form-group mb-2">
        {{create_group_form.group_name}}
      </div>
      <input type="submit" class="btn btn-secondary mb-2" value="Create Group">
    </form>
  </div>
</div>
<hr />
<div class="row">
  <div class="col-sm-12 col-md-6">
    <h2>Gift List</h2>
    <!-- Gift List -->
    <ul class="list-group">
      {%  for gift in gifts %}
      <li class="list-group-item d-flex align-items-center justify-content-between"><a href="#">{{gift.name}}</a> <a
          class="btn btn-danger" href="{% url 'giftlist:deletegift' gift.id %}">X</a></li>
      {% endfor %}
    </ul>
  </div>
  <div class="col-sm-12 col-md-6">
    <h2>Add Gift</h2>
    <!-- Add Gift Form -->
    <form action="{% url 'giftlist:home' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        {{add_gift_form.name.label_tag}}
        {{add_gift_form.name}}
      </div>
      <div class="form-group">
        {{add_gift_form.price.label_tag}}
        {{add_gift_form.price}}
      </div>
      <div class="form-group">
        {{add_gift_form.link.label_tag}}
        {{add_gift_form.link}}
      </div>
      <input type="submit" class="btn btn-primary" value="Add">
    </form>
  </div>
</div>
{% endblock %}

django/giftlist/templates/giftlist/membergiftlist.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center">{{member}}'s Gift List</h1>

  <ul class="list-group">
    {%  for gift in gifts %}
			<li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="#">{{gift.name}}</a>
        {% if gift.selected == False %}
        <a class="btn btn-success" href="{% url 'giftlist:addshoppinglist' member gift.id %}">Add</a>
        {% endif %}
      </li>
		{% endfor %}
  </ul>

{% endblock %}